### ISSUE TITLE
Agregar su correo al README

### ISSUE THREAD

**Issue by profealejandroduoc** [profealejandroduoc/markejercicio#2]
# Todos deben agregar su correo al README
**si no quedan fuera del grupo**

- [x] Cesar @ErrorCute 
- [x] Isak @bravoisaac 
- [x] El jefe @F-C-U 

![Captura de pantalla 2024-02-20 174749](https://github.com/profealejandroduoc/markejercicio/assets/101122095/1e18f93c-cc43-496e-977d-094cf82ed7c4)

**Comment by F-C-U** [comment]
ola tonotos
